apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pocketbase
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
    - host: api.justsend.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pocketbase
                port:
                  number: 8090
  tls:
    - hosts:
        - api.justsend.cloud
      secretName: pocketbase-tls
